import 'package:flutter/material.dart';

Color blackText = const Color(0xff000000);
Color whiteText = const Color(0xffFFFFFF);
Color greyText = const Color(0xff808080);
Color weatheredStone = const Color(0xffC4C4C4);
Color sapphireGlitter = const Color(0xff0C35C6);
Color veteranBlue = const Color(0xff2A52E2);
Color springForth = const Color(0xff0EB51F);
Color spanishGrey = const Color(0xff979797);
Color hooloovooBlue = const Color(0xff3B5AFB);
Color royalBlue = const Color(0xff4169E1);
Color biopunk = const Color(0xff60f248);
Color icyLilac = const Color(0xffE7E7F6);
Color boyRed = const Color(0xffB50E18);
Color blobfish = const Color(0xffFFC1CC);
Color superSilver = const Color(0xffEEEEEE);
Color blackOak = const Color(0xff4E4E4E);
Color antiqueTin = const Color(0xff6E6E71);
Color scarabaeusSacer = const Color(0xff414141);
Color prettyPosie = const Color(0xffBFBFE3);
Color widowmaker = const Color(0xff93A4FF);
Color glowingBrakeDisc = const Color(0xffF24848);
Color poisonousIceCream = const Color(0xffDDDC24);
Color mithril = const Color(0xff878787);
Color sapphireGlitter = const Color(0xff0C35C6);